inherit_from: ../../clotho_v2/waveform/test.yaml

output_path: ensemble_output/2trm_4trm_gru
experiment_path:
    [
        "experiments/clotho_v2/train_val/TransformerModel/cnn14rnn_trm/seed_1/swa.pth",
        "experiments/clotho_v2/train_val/TransformerModel/cnn14rnn_4trm/seed_1/swa.pth",
        "experiments/clotho_v2/train_val/FcModel/cnn14rnn_gru/seed_1/swa.pth"
    ]


inference_args:
    method: beam # "greedy", "beam", "gumble"
    beam_size: 3
    beam_temp: 1
    n_best: False
    n_best_size: 5
    sample_word_temp: 1
    max_length: 20

caption_output: predictions/swa_beam3.json
score_output: results/swa_beam3.txt
zh: False
