outputpath: experiments/clotho_v2/train_val

data:
    train:
        dataset:
            type: CaptionDataset
            args:
                features:
                    wav: data/clotho_v2/dev/waveform_32k.csv
                transforms:
                    wav: Null
                caption: data/clotho_v2/dev/text.json
                vocabulary: data/clotho_v2/dev/vocab.pkl
        collate_fn:
            type: collate_fn
            args:
                pad_keys: [wav, cap]
                sort_key: cap
        dataloader_args:
            shuffle: True
            batch_size: 32
            num_workers: 4
    val:
        dataset:
            type: InferenceDataset
            args:
                features:
                    wav: data/clotho_v2/val/waveform_32k.csv
                transforms:
                    wav: Null
        collate_fn:
            type: collate_fn
            args:
                pad_keys: [wav]
        caption: data/clotho_v2/val/text.json
        dataloader_args:
            shuffle: False
            batch_size: 32
            num_workers: 4

zh: False
