inherit_from: ./train_data.yaml

remark: cnn14rnn_trm

# sync_file: /mnt/lustre/sjtu/home/xnx98/work/AudioCaption/ddp_sync/sync

model:
    encoder:
        type: Cnn14RnnEncoder
        args:
            sample_rate: 32000
            pretrained: sed/audioset_tagging_cnn/pretrained_weights/Cnn14_mAP=0.431.pth
            freeze_cnn: True
            freeze_cnn_bn: True
            bidirectional: True
            hidden_size: 256
            dropout: 0.5
            num_layers: 3
    decoder:
        type: TransformerDecoder
        args:
            emb_dim: 256
            fc_emb_dim: 512
            attn_emb_dim: 512
            nlayers: 2
            dropout: 0.2
    type: TransformerModel
    args: {}
    # sync_bn: True

specaug: False

optimizer:
    type: Adam
    args:
        lr: !!float 5e-4
        weight_decay: !!float 1e-6

lr_scheduler:
    type: ExponentialDecayScheduler
    args:
        # warmup_iters: 3000
        final_lrs: !!float 5e-7


trainer:
    max_grad_norm: 1.0
    epochs: 25
    save_interval: 5
    lr_update_interval: iteration
    monitor_metric:
        name: score
        mode: max
    include_optim_in_ckpt: False
    finetune: True

inference_args:
    sample_method: beam
    beam_size: 3

scheduled_sampling:
    use: True
    mode: linear
    final_ratio: 0.7

loss:
    type: LabelSmoothingLoss
    args:
        smoothing: 0.1

swa:
    use: True
    start: 21
