wandb_version: 1

trial_series:
  desc: null
  value: /home/ubuntu/dcase2023-audio-retrieval/output/
trial_base:
  desc: null
  value: /home/ubuntu/dcase2023-audio-retrieval/output/
data_conf:
  desc: null
  value:
    train_data:
      dataset: /home/ubuntu/audio-captioning-and-audio-retrieval/openl3_model/data
      audio_data: development_audio_logmels_openl3.hdf5
      text_data: development_text.csv
      text_embeds: roberta_embeds.pkl
      text_level: sentence
    val_data:
      dataset: /home/ubuntu/audio-captioning-and-audio-retrieval/openl3_model/data
      audio_data: validation_audio_logmels_openl3.hdf5
      text_data: validation_text.csv
      text_embeds: roberta_embeds.pkl
      text_level: sentence
    eval_data:
      dataset: /home/ubuntu/audio-captioning-and-audio-retrieval/openl3_model/data
      audio_data: evaluation_audio_logmels_openl3.hdf5
      text_data: evaluation_text.csv
      text_embeds: roberta_embeds.pkl
      text_level: sentence
param_conf:
  desc: null
  value:
    num_epoch: 80
    batch_size: 32
    model: DualEncoderModel
    criterion: infonce_loss
    optimizer: AdamOptimizer
    lr_scheduler: ReduceLROnPlateau
DualEncoderModel:
  desc: null
  value:
    name: DualEncoderModel
    out_norm: L2
    audio_enc:
      name: OpenL3Embeddings
      init: nonprior
      weight: /home/ubuntu/dcase2023-audio-retrieval/data/pretrained_models/CNN14_300.pth
      trainable: true
      out_dim: 300
    text_enc:
      name: SentBERTBaseEncoder
      init: prior
      out_dim: 300
criteria:
  desc: null
  value:
    infonce_loss:
      name: LogSoftmaxLoss
      args:
        temperature: 0.07
        dist: dot_product
AdamOptimizer:
  desc: null
  value:
    name: Adam
    args:
      lr: 0.001
      weight_decay: 0.0
ReduceLROnPlateau:
  desc: null
  value:
    name: ReduceLROnPlateau
    args:
      mode: min
      factor: 0.1
      patience: 5
      threshold: 0.005
      threshold_mode: abs
      min_lr: 1.0e-06
      verbose: true
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681937012.260939
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.14.2
      6: 4.24.0
      8:
      - 5
