inherit_from: ../data_waveform.yaml

remark: scst/cnn14rnn_2trm

model:
    encoder:
        type: Cnn14RnnEncoder
        args:
            sample_rate: 32000
            pretrained: sed/audioset_tagging_cnn/pretrained_weights/Cnn14_mAP=0.431.pth
            bidirectional: True
            hidden_size: 256
            dropout: 0.5
            num_layers: 3
    decoder:
        type: TransformerDecoder
        args:
            emb_dim: 256
            fc_emb_dim: 512
            attn_emb_dim: 512
            nlayers: 2
            dropout: 0.2
    type: TransformerModel
    args: {}
    pretrained: experiments/dcase2022/TransformerModel/clap_cnn14_rnn_2trm/seed_1/swa.pth

modelwrapper:
    type: ScstWrapper
    args: {}

specaug: False

optimizer:
    type: Adam
    args:
        lr: !!float 5e-5
        weight_decay: !!float 0.0

lr_scheduler:
    type: ExponentialDecayScheduler
    args:
        warmup_iters: 0
        final_lrs: !!float 5e-5


trainer:
    max_grad_norm: 1.0
    epochs: 100
    save_interval: 10
    lr_update_interval: iteration
    monitor_metric:
        name: score
        mode: max
    include_optim_in_ckpt: False


inference_args:
    sample_method: beam
    beam_size: 3


scheduled_sampling:
    use: False
    mode: linear
    final_ratio: 0.7

loss:
    type: LabelSmoothingLoss
    args:
        smoothing: 0.1

swa:
    use: True
    start: 96
